### ISSUE TITLE
Auth token support

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/push-to-registry#1]
We should support tokens as well as username/password.

**Comment by lstocchi** [comment]
In quay (and by reading quickly the same in dockerhub) the token should be passed as password. Am i missing something? 

- https://docs.docker.com/docker-hub/access-tokens/
- https://docs.quay.io/glossary/robot-accounts.html

**Comment by tetchel** [comment]
Cool we can just add a note to the `password` input in the readme, then

**Comment by tetchel** [comment]
done
