### ISSUE TITLE
Support --digestfile parameter

### ISSUE THREAD

**Issue by fglaeser** [redhat-actions/push-to-registry#11]
I need to get the digest after push in order to be able to deploy the image based on digest rather than the tag.

**Comment by tetchel** [comment]
Sure, would adding the `digest` to the Action Output be an okay way to do this, or do you definitely want to write it to a file? (or we can do both).

**Comment by fglaeser** [comment]
Ana output Will be ok for me. Thanks

**Comment by fglaeser** [comment]
@tetchel  Hi !!!, do you have an estimated date for the release of this?

**Comment by tetchel** [comment]
hi, how does this look? I added the `digestfile` argument, which is filled with a default if not provided, and the contents of that file are also output as `digest`.

https://github.com/redhat-actions/push-to-registry/runs/1665748750

**Comment by fglaeser** [comment]
@tetchel It look great!! Exactly what I need.
