### ISSUE TITLE
s2i-build + push-to-registry. Update image problem in Selfhosted runner.

### ISSUE THREAD

**Issue by fglaeser** [redhat-actions/push-to-registry#12]
Hi in some test I've used s2i-build + push-to registry in a selfhosted runner and I think there is a problem when you build the image for second time. What I saw in the source code is if there is no image in the podman registry, the action try to pull the image from the docker registry, thas works ok the first time because the s2i-build leaves the created image in the docker registry. The second time, s2i-build creates a new version of the image in the docker registry, but when the push-to-registry action get the images form de podman registry, the image already exist, so the push-to-registry push again the previous version of the image and not the new one. I' ve mitigated this runing "podman rmi name:tag" after the push.

**Comment by tetchel** [comment]
Thank you for reporting this - we will check it out.

**Comment by tetchel** [comment]
The problem is that a docker-built image will be pulled into the podman image storage, but only if it doesn't exist there already.

https://github.com/redhat-actions/push-to-registry/blob/main/src/index.ts#L35
