### ISSUE TITLE
Add back (singular) registry-path output

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/push-to-registry#29]
I've found myself wishing we still had the old behaviour which output a single registry path only. This was easier to pass to subsequent steps than parsing the json and selecting [0]. 

We can add back the old `registry-path` output which just contains `registry-paths[0]`. This has an added bonus of making v1 -> v2 migration easier.

**Comment by Divyansh42** [comment]
This is going to be helpful, I avoid using `v2` version due to this extra step of parsing :sweat_smile: 
Thanks for pointing it out.
