### ISSUE TITLE
Checking docker image storage looks like an error, even when it isn't

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/push-to-registry#32]
I know I signed off on this behaviour previously but the more I see it in my workflows the less I like it:

![image](https://user-images.githubusercontent.com/8888438/109669410-0e1f7c80-7b40-11eb-8753-dd5ee20fb2f8.png)

Checking the docker storage and not finding the image is normal operation, and not an error so long as the image is in podman.

I would like it if we grouped this output or checked for this error specifically, so that a regular workflow didn't have "Error" so prominently displayed in it. 

However if any error other than this one occurs, it should be obvious.

**Comment by Divyansh42** [comment]
Done in #34
