### ISSUE TITLE
Fail the action if input `image` contains any `/` in it's name.

### ISSUE THREAD

**Issue by Divyansh42** [redhat-actions/push-to-registry#38]
There might be case when user provide `/` in the image name. 
Example: `namespace/imageName` 
If above image is provided then the action will fail to push the image to registry (only valid when image is present in docker storage)
So, We should throw an error and fail the action right away, stating `/` is not allowed in the image name

Ref: #37

**Comment by andmos** [comment]
It's and easy mistake to make, since lots of people building local images on their own computers do it in the form `docker build -t namespace/imagename .`, so it should be quite clear if it's not supported 👍

**Comment by Divyansh42** [comment]
Yeah, we will try to make it clear in the documentation too.
