### ISSUE TITLE
[Workflow] Add CRDA scan step in the CI workflow

### ISSUE THREAD

**Issue by divyansh42** [redhat-actions/push-to-registry#51]
As we have new [CRDA action](https://github.com/redhat-actions/crda/) now, I think it is useful for our CI checks to have CRDA scan step so that we can run vulnerabilities scan on dependencies updates.

**Comment by Hk00998877** [comment]
[上传uk.co.ve #uk.co.vedaconsulting.mosaico-2.8.1637146864.z

**Comment by jereytucker** [comment]
@ @ # #68
