### ISSUE TITLE
Failing to push image to ghcr.io: 403 (Forbidden)

### ISSUE THREAD

**Issue by J3RN** [redhat-actions/push-to-registry#52]
Luckily I managed to figure out this issue, but I wanted to write about it so that other could find it.

### Issue

In the `step` using this action, I would receive the following error from Podman:
```
Error: trying to reuse blob sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116 at destination: failed to read from destination repository my_org/my_image: 403 (Forbidden)
```

### Solution

This was a pre-existing package that I'm simply trying to automate the workflow around. The solution lied in permissions _on the package_. Namely, I needed to:
1. Navigate to the package
2. Click "Package settings" on the right side
  ![image](https://user-images.githubusercontent.com/2058614/137406807-701a96e5-1980-4366-8454-b388fe1f525c.png)
3. Add the repository running the GitHub Action in the "Manage Actions access" section
  ![image](https://user-images.githubusercontent.com/2058614/137406873-56ebb1a6-100e-4907-88ea-22dec1c26116.png)

_Voila!_ It works now.

**Comment by tetchel** [comment]
Thanks, I added this to the troubleshooting.

**Comment by bollian** [comment]
As someone who is trying to publish a container for the first time and thus doesn't have access to the packages button in the sidebar, what am I supposed to do?

**Comment by tetchel** [comment]
I think in the past, I pushed my first version of an image from the command line myself, rather than having Actions do it.
