### ISSUE TITLE
[FEATURE] set build context directory

### ISSUE THREAD

**Issue by pfeifferj** [redhat-actions/push-to-registry#88]
### Is your feature request related to a problem? Please describe.

The following scenario seems not to be supported as of yet:

Containerfile + artifacts in a build directory

```bash
.
├── build
│   ├── Containerfile
│   └── setup.sh
```

Containerfile copying artifact from the build directory

```Containerfile
(...)
COPY setup.sh .
(...)
```

The current setup seems to only query the root directory, rather than the build directory:

```bash
error building at STEP "COPY setup.sh .": checking on sources under "/home/runner/work/<repo-name>/<repo-name>": copier: stat: "/setup.sh": no such file or directory
```

### Describe the solution you'd like

Add an option to set a build context directory

**Comment by travier** [comment]
This is the push action. You want https://github.com/redhat-actions/buildah-build which has the  `context` option.
